### ISSUE TITLE
Uncaught OutOfRangeException: Current architecture (aarch64) may not be supported

### ISSUE THREAD

**Issue by andrei-dascalu** [spiral/roadrunner-cli#9]
Hello,

I am using an M1 Macbook trying out Symfony 5 with Roadrunner. In my local machine setup, everything works as expected.

However, when I'm trying to build my project into Docker, on pulling the RR binary (`vendor/bin/rr get --location /usr/local/bin`) I am getting this error:

```bash
Fatal error: Uncaught OutOfRangeException: Current architecture (aarch64) may not be supported in /app/vendor/spiral/roadrunner-cli/src/Environment/Architecture/Factory.php:57
```

```Dockerfile
FROM php:8-alpine

WORKDIR /scripts
COPY ./ops/install.composer.sh .

RUN chmod +x ./install.composer.sh \
    && apk update \
    && apk add zip unzip curl-dev curl wget libzip-dev \
    && docker-php-ext-install sockets zip curl \
    && ./install.composer.sh
    
WORKDIR /app
COPY . /app

RUN rm -rf vendor && composer install -o --no-scripts \
    && vendor/bin/rr get --location /usr/local/bin \
    && chmod +x /usr/local/bin/rr

EXPOSE 8080

ENTRYPOINT ["/bin/sh", "-c", "rr serve -c .rr.dev.yaml"]
```

`aarch64` refers to the same thing as `arm64` (though I'm not sure why the particular range of arm images used by php identify as `aarch64` when their very base images often identify as `arm64`

I wonder if RR-CLI should accept either? 
I've made a test by adding this arch into `vendor/spiral/roadrunner-cli/src/Environment/Architecture/Factory.php` and it seems to work as expected, no issues when running via aarch64 Docker image.

Cheers

**Comment by andrei-dascalu** [comment]
Solved via merge. Thanks @SerafimArts

**Comment by SerafimArts** [comment]
@andrei-dascalu however, please note that the PR itself, although it solves the problem, is not entirely correct.

Pay attention to this line: https://github.com/spiral/roadrunner-cli/blob/master/src/Environment/Architecture/Factory.php#L34

This means that running this code on the arm64 architecture will return amd64. This solves the problem, but is a bug:
```php
(new Factory())->fromGlobals(); // amd64
```

I have accepted your PR because this solves the indicated problem in issue, but if you have the opportunity, please correct it, since at the moment I do not have time to correct it.

P.S. The problem itself arose here https://github.com/spiral/roadrunner-cli/pull/5, since I didn't see her for the first time during the review
